parameters:
#    jdd_op_app.example.class: JeffreyDD\OpkomstAppBundle\Example

services:
#    jdd_op_app.example:
#        class: %jdd_op_app.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
